### ISSUE TITLE
About mask

### ISSUE THREAD

**Issue by Happy-life-echo** [aL3x-O-o-Hung/CAT-Net#9]
Sorry to bother you again, last time you answered my question about the source of mask. Retrieved from: https://github.com/ykl-ucla/prostate_zonal_seg.

I downloaded the data and studied it. But there are still some questions:
There are two types of labels in the mask, but their boundaries are represented by 255 pixels. So, how do we distinguish which boundary is label1 and which one is label2? Because in some other datasets, different labels are usually represented by different pixels (0,1,2...).

I'd like to know how you do it and look forward to your answer. Thank you so much~

**Comment by aL3x-O-o-Hung** [comment]
Hi, thanks for the question. In the labels given in https://github.com/ykl-ucla/prostate_zonal_seg, one is actually given by 1 and the other is given by 2 (in pixel values). I think they only labeled the boundaries as 255 for better visualization. Hope this helps and please let me know if you have any further questions.

**Comment by Happy-life-echo** [comment]
Thanks for your answer, it's very helpful to me.
